project:
  type: book
  output-dir: docs

book:
  title: "Physics 1 - Mechanics"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/physics1/
  favicon: archive/logo.png

  # date: "29.3.2025"
  chapters:
    - index.qmd
    - part: "topics"
      chapters:
      - lecture-notes.qmd
      - extra/extra-basic-math.qmd
      - extra/extra-units.qmd
      - extra/extra-1d-kinematics.qmd
      - extra/extra-momentum.qmd
    - part: "the good stuff"
      chapters:
      - gifs/cartoons.qmd
      - gifs/units.qmd
      - gifs/kinematics.qmd
      - gifs/newtons-laws.qmd
      - gifs/linear-momentum.qmd
      - gifs/energy.qmd
      - gifs/fluids.qmd
      - gifs/wow.qmd
    - exams.qmd
    - more.qmd
  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
    logo: archive/logo.png
  search: true

# bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    # css: styles.css
    fontsize: 1.2em
    highlight-style: kate-custom.theme #kate #solarized # kate # tango # breeze # ayu # monokai # breezedark # espresso
    include-in-header:
      - includes.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    fig-align: center
    # the default MathJax rendering option yields ugly results, use katex
    html-math-method: katex
  
  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex



