## exams {.unnumbered}
Some past exams (in hebrew):

| Year | Midterm | Moed A | Moed B | Moed C |
|:---:|:---:|:---:|:---:|:---:|
| 2021-2022 | [{{< iconify bi question-square-fill >}}](/archive/exams/2022-71031-bochan.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2022-71031-bochan-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2022-71031-moed-A.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2022-71031-moed-A-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2022-71031-moed-B.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2022-71031-moed-B-solution.pdf) |
| 2020-2021 | [{{< iconify bi question-square-fill >}}](/archive/exams/2021-71031-bochan.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2021-71031-bochan-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2021-71031-moed-A.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2021-71031-moed-A-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2021-71031-moed-B.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2021-71031-moed-B-solution.pdf) |
| 2019-2020 | [{{< iconify bi question-square-fill >}}](/archive/exams/2020-71031-bochan.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2020-71031-bochan-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2020-71031-moed-A.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2020-71031-moed-A-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2020-71031-moed-B.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2020-71031-moed-B-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2020-71031-moed-C.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2020-71031-moed-C-solution.pdf) |
| 2018-2019 | [{{< iconify bi question-square-fill >}}](/archive/exams/2019-71031-bochan.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2019-71031-bochan-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2019-71031-moed-A.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2019-71031-moed-A-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2019-71031-moed-B.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2019-71031-moed-B-solution.pdf) |
| 2017-2018 | [{{< iconify bi question-square-fill >}}](/archive/exams/2018-71031-bochan.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2018-71031-bochan-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2018-71031-moed-A.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2018-71031-moed-A-solution.pdf) | [{{< iconify bi question-square-fill >}}](/archive/exams/2018-71031-moed-B.pdf) &ensp; [{{< iconify bi exclamation-square >}}](/archive/exams/2018-71031-moed-B-solution.pdf) |